### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by owain-stratton** [geoshepherds/ahkw_website#12]
- [x] W3C Validate

- [x] Meta tags, meta og tags, html lang attribute and title tags

- [x] sitemap.xml

- [x] favicon and iphone favicon

- [ ] Check all links work

- [x] Google Analytics

- [x] 404 redirect page

- [x] 301 redirect page

- [x] Minify css and js

Cross browser checks:

- [x] firefox

- [x] safari

- [x] chrome

- [ ] IE/Edge

Device checks:

- [ ] Android

- [x] iOS

Back-end checks:

- [x] htaccess file
